---

- name: Run file commands
  hosts: all
  gather_facts: false

  tasks:
    - name: Create a directory
      file:
        path: /home/smaya/myfolder
        state: directory
        owner: smaya
        group: smaya




